# Generated by Django 4.0.3 on 2022-04-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surf_report', '0003_rename_links_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
